services:
  mongo:
    image: mongo:5.0
    command: mongod
    networks:
      - all
  web:
    image: edwin/ec7233nodeapp:lts-jod

    ports:
      - "8080:3000"
    depends_on:
      - mongo
    restart: always
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/accounts"
networks:
  all: